services:
  psql_bp:
    image: docker.io/postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
    networks:
      - blueprint_network
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  udp_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - blueprint_network
    ports:
      - 9095:9095/udp
    depends_on:
      - psql_bp

networks:
  blueprint_network:
    driver: bridge
volumes:
  psql_volume_bp:
